### PR TITLE
feat: allow user to exclude date-fns locales

### LINKED ISSUE #10: Let user configure locale so we don't include all of date-fns/locale
Probably by not including it by default and letting user overwrite its own somewhat like this:

```js
import allLocales from 'date-fns/locale';
import deLocale from 'date-fns/locale/de';

// just load all, will bloat size
const locales = allLocales;

// just load one locale
const locales = {
  de: Locale
}

export default class PowerCalendarDays extends DaysComponent {
  locales;
}
```

This would also allow users to not use date-fns locales but also custom implementations, based on already used intl frameworks.

I think that there's also an easier solution.
We could extract the date-fns/locale methods into a separate module and depending on the addon config, filter that module and use the unlocalized base instead.

### PR DESCRIPTION
**Pull request by makepanic**
fixes #10

### CODE REVIEW

**Comment by makepanic** [comment]
Seems to work pretty ok:

`includeLocales: false`:

```
 - dist/assets/auto-import-fastboot-d41d8cd98f00b204e9800998ecf8427e.js: 0 B
 - dist/assets/dummy-24d7944e15f99e05678d9e09d0203a31.js: 8.58 KB (1.57 KB gzipped)
 - dist/assets/dummy-b06e59e1e6434f2b63545acf31a714e4.css: 4.02 KB (779 B gzipped)
 - dist/assets/vendor-363b24984561140a5702529d7e4d5c16.js: 617.91 KB (153.07 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

`includeLocales: false`/ default:

```
 - dist/assets/auto-import-fastboot-d41d8cd98f00b204e9800998ecf8427e.js: 0 B
 - dist/assets/dummy-24d7944e15f99e05678d9e09d0203a31.js: 8.58 KB (1.57 KB gzipped)
 - dist/assets/dummy-b06e59e1e6434f2b63545acf31a714e4.css: 4.02 KB (779 B gzipped)
 - dist/assets/vendor-2b7acada006de9e5e0c3133ec98debf7.js: 977.56 KB (216.12 KB gzipped)
 - dist/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css: 0 B
```

**Comment by makepanic** [comment]
@veelci when localizing the calendar, do you want to have all possible translations available or would it be ok to provide a list of locales that will be included from `date-fns/locales/*`?

e.g. `['de', 'fr', 'it', 'en']`

It seems like a full locale build bundles ~360 KB more JS.

**Comment by makepanic** [comment]
Nvm it was super easy to also allow a list of locales, so the developer can configure which date-fns locales to include, see https://github.com/makepanic/ember-power-calendar-date-fns/blob/e83361c6e403951b1282f2e3f6e41b9a52d855df/README.md#using-date-fnslocale

**Comment by makepanic** [comment]
released as `0.3.1`

**Comment by veelci** [comment]
Thank you.

**Pull request merged**
