### PR TITLE
Update README and CHANGELOG

### PR DESCRIPTION
**Pull request by veelci**
Updates the README to correct the import of the days component and the CHANGELOG to include my previous PR.

### CODE REVIEW

**Comment by makepanic** [comment]
Thanks, sorry that i forgot to add your commit. I usually use https://www.conventionalcommits.org/en/v1.0.0-beta.4/ and generate the changelog based on that. I didn't check if all commits followed conventional-commits :( 

Can you maybe try to split the PR up, it seems like all of the PR contain all of your commits.
If possible also use conventional-commit messages, e.g. `docs: correct import in README`.

**Comment by veelci** [comment]
Yeah.  I'll break the commits up.

**Comment by makepanic** [comment]
I've merged your PRs. 
I'll make some adjustments to get CI to be green and will cut a new release then.

**Comment by veelci** [comment]
Yeah, through npm.  Thanks - I've modified my config.

**Pull request closed without merging**
